/// `coast cert` command — inspect and export the active install's Caddy root certificate.
use std::fs;
use std::io::Read;
use std::path::{Path, PathBuf};

use anyhow::{bail, Context, Result};
use base64::Engine;
use clap::{Args, Subcommand};
use colored::Colorize;
use sha2::{Digest, Sha256};

#[derive(Debug, Args)]
pub struct CertArgs {
    #[command(subcommand)]
    pub action: CertAction,
}

#[derive(Debug, Subcommand)]
pub enum CertAction {
    /// Show the active Coast home, root cert path, and fingerprint if present.
    Info,
    /// Print the absolute path to the active install's root certificate.
    Path,
    /// Print the SHA-256 fingerprint of the active install's root certificate.
    Fingerprint,
    /// Copy the active install's root certificate to a destination path.
    Export {
        /// Destination path for the exported certificate.
        #[arg(long)]
        to: PathBuf,
    },
}

pub async fn execute(args: &CertArgs) -> Result<()> {
    match &args.action {
        CertAction::Info => execute_info(),
        CertAction::Path => execute_path(),
        CertAction::Fingerprint => execute_fingerprint(),
        CertAction::Export { to } => execute_export(to),
    }
}

fn active_coast_home() -> Result<PathBuf> {
    coast_core::artifact::coast_home().context("Could not determine Coast home directory")
}

fn root_cert_path() -> Result<PathBuf> {
    Ok(active_coast_home()?.join("caddy/pki/authorities/local/root.crt"))
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum CertPathState {
    ReadableFile,
    Missing,
    Unreadable,
}

fn cert_path_state(path: &Path) -> Result<CertPathState> {
    match fs::metadata(path) {
        Ok(metadata) => {
            if metadata.is_file() {
                Ok(CertPathState::ReadableFile)
            } else {
                bail!("Root certificate path is not a file: {}", path.display());
            }
        }
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(CertPathState::Missing),
        Err(error) if error.kind() == std::io::ErrorKind::PermissionDenied => {
            Ok(CertPathState::Unreadable)
        }
        Err(error) => Err(error)
            .with_context(|| format!("Failed to inspect root certificate at {}", path.display())),
    }
}

fn ensure_cert_readable(path: &Path) -> Result<()> {
    match cert_path_state(path)? {
        CertPathState::ReadableFile => Ok(()),
        CertPathState::Missing => bail!(
            "No Coast root certificate found at {}.\nRun a Coast project with a Caddy-backed HTTPS service once to generate it.",
            path.display()
        ),
        CertPathState::Unreadable => bail!(
            "A Coast root certificate exists at {} but is not readable by the current user.\nIf it was generated by an older Coast run, recreate the HTTPS instance with the updated daemon and try again.",
            path.display()
        ),
    }
}

fn read_fingerprint(path: &Path) -> Result<String> {
    ensure_cert_readable(path)?;
    let mut file = fs::File::open(path)
        .with_context(|| format!("Failed to open root certificate at {}", path.display()))?;
    let mut bytes = Vec::new();
    file.read_to_end(&mut bytes)
        .with_context(|| format!("Failed to read root certificate at {}", path.display()))?;
    let cert_bytes = certificate_bytes(&bytes)
        .with_context(|| format!("Failed to parse root certificate at {}", path.display()))?;
    let mut hasher = Sha256::new();
    hasher.update(cert_bytes);
    Ok(hex::encode(hasher.finalize()))
}

fn certificate_bytes(bytes: &[u8]) -> Result<Vec<u8>> {
    const PEM_BEGIN: &str = "-----BEGIN CERTIFICATE-----";
    const PEM_END: &str = "-----END CERTIFICATE-----";

    if let Ok(pem) = std::str::from_utf8(bytes) {
        if let Some(begin) = pem.find(PEM_BEGIN) {
            let end = pem[begin..]
                .find(PEM_END)
                .map(|idx| begin + idx)
                .context("Root certificate PEM is missing END CERTIFICATE")?;
            let body = &pem[begin + PEM_BEGIN.len()..end];
            let base64_body: String = body.chars().filter(|c| !c.is_whitespace()).collect();
            if base64_body.is_empty() {
                bail!("Root certificate PEM body is empty");
            }

            return base64::engine::general_purpose::STANDARD
                .decode(base64_body)
                .context("Root certificate PEM body is not valid base64");
        }
    }

    Ok(bytes.to_vec())
}

fn execute_info() -> Result<()> {
    let coast_home = active_coast_home()?;
    let cert_path = root_cert_path()?;

    println!("Active Coast home: {}", coast_home.display());
    println!("Root cert path:    {}", cert_path.display());

    match cert_path_state(&cert_path)? {
        CertPathState::ReadableFile => {
            println!("Exists:             yes");
            println!("Readable:           yes");
            println!("Fingerprint:        {}", read_fingerprint(&cert_path)?);
        }
        CertPathState::Missing => {
            println!("Exists:             no");
            println!("Guidance:           run a Coast project with a Caddy-backed HTTPS service once to generate it");
        }
        CertPathState::Unreadable => {
            println!("Exists:             yes");
            println!("Readable:           no");
            println!("Guidance:           recreate the HTTPS instance with the updated daemon, then retry");
        }
    }

    Ok(())
}

fn execute_path() -> Result<()> {
    let path = root_cert_path()?;
    ensure_cert_readable(&path)?;
    println!("{}", path.display());
    Ok(())
}

fn execute_fingerprint() -> Result<()> {
    let path = root_cert_path()?;
    println!("{}", read_fingerprint(&path)?);
    Ok(())
}

fn execute_export(destination: &Path) -> Result<()> {
    let source = root_cert_path()?;
    ensure_cert_readable(&source)?;

    if let Some(parent) = destination.parent() {
        fs::create_dir_all(parent).with_context(|| {
            format!(
                "Failed to create destination directory {}",
                parent.display()
            )
        })?;
    }

    fs::copy(&source, destination).with_context(|| {
        format!(
            "Failed to export root certificate from {} to {}",
            source.display(),
            destination.display()
        )
    })?;

    println!(
        "{} Exported Coast root certificate to {}",
        "ok".green().bold(),
        destination.display()
    );
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use clap::Parser;
    use std::ffi::OsString;
    use std::sync::{Mutex, OnceLock};

    #[derive(Debug, Parser)]
    struct TestCli {
        #[command(flatten)]
        args: CertArgs,
    }

    fn coast_home_env_lock() -> &'static Mutex<()> {
        static LOCK: OnceLock<Mutex<()>> = OnceLock::new();
        LOCK.get_or_init(|| Mutex::new(()))
    }

    struct CoastHomeGuard {
        prev: Option<OsString>,
    }

    impl CoastHomeGuard {
        fn set(path: &Path) -> Self {
            let prev = std::env::var_os("COAST_HOME");
            unsafe {
                std::env::set_var("COAST_HOME", path);
            }
            Self { prev }
        }
    }

    impl Drop for CoastHomeGuard {
        fn drop(&mut self) {
            match &self.prev {
                Some(value) => unsafe { std::env::set_var("COAST_HOME", value) },
                None => unsafe { std::env::remove_var("COAST_HOME") },
            }
        }
    }

    fn with_temp_coast_home<T>(f: impl FnOnce(&Path) -> T) -> T {
        let _lock = coast_home_env_lock()
            .lock()
            .unwrap_or_else(|poisoned| poisoned.into_inner());
        let tmp = tempfile::tempdir().unwrap();
        let _env = CoastHomeGuard::set(tmp.path());
        f(tmp.path())
    }

    fn write_cert(path: &Path, contents: &[u8]) {
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).unwrap();
        }
        fs::write(path, contents).unwrap();
    }

    #[test]
    fn test_cert_info_parse() {
        let cli = TestCli::try_parse_from(["test", "info"]).unwrap();
        assert!(matches!(cli.args.action, CertAction::Info));
    }

    #[test]
    fn test_cert_path_parse() {
        let cli = TestCli::try_parse_from(["test", "path"]).unwrap();
        assert!(matches!(cli.args.action, CertAction::Path));
    }

    #[test]
    fn test_cert_fingerprint_parse() {
        let cli = TestCli::try_parse_from(["test", "fingerprint"]).unwrap();
        assert!(matches!(cli.args.action, CertAction::Fingerprint));
    }

    #[test]
    fn test_cert_export_parse() {
        let cli = TestCli::try_parse_from(["test", "export", "--to", "/tmp/foo.crt"]).unwrap();
        match cli.args.action {
            CertAction::Export { to } => assert_eq!(to, PathBuf::from("/tmp/foo.crt")),
            _ => panic!("expected export"),
        }
    }

    #[test]
    fn test_root_cert_path_uses_coast_home_env() {
        with_temp_coast_home(|home| {
            let path = root_cert_path().unwrap();
            assert_eq!(
                path,
                home.join("caddy")
                    .join("pki")
                    .join("authorities")
                    .join("local")
                    .join("root.crt")
            );
        });
    }

    #[test]
    fn test_root_cert_path_differs_across_install_homes() {
        let first = with_temp_coast_home(|_| root_cert_path().unwrap());
        let second = with_temp_coast_home(|_| root_cert_path().unwrap());
        assert_ne!(first, second);
    }

    #[test]
    fn test_read_fingerprint_known_value_for_der() {
        with_temp_coast_home(|home| {
            let path = home.join("root.der");
            write_cert(&path, b"hello cert\n");
            let fingerprint = read_fingerprint(&path).unwrap();
            assert_eq!(
                fingerprint,
                "b453247dea083483635b7bbde22579f7d4e0d2daa4fd58b96775c88f88d161c4"
            );
        });
    }

    #[test]
    fn test_read_fingerprint_hashes_pem_payload_not_file_bytes() {
        with_temp_coast_home(|home| {
            let path = home.join("root.crt");
            write_cert(
                &path,
                b"-----BEGIN CERTIFICATE-----\naGVsbG8gY2VydAo=\n-----END CERTIFICATE-----\n",
            );
            let fingerprint = read_fingerprint(&path).unwrap();
            assert_eq!(
                fingerprint,
                "b453247dea083483635b7bbde22579f7d4e0d2daa4fd58b96775c88f88d161c4"
            );
        });
    }

    #[test]
    fn test_read_fingerprint_ignores_pem_wrapping_whitespace() {
        with_temp_coast_home(|home| {
            let compact = home.join("compact.crt");
            let wrapped = home.join("wrapped.crt");
            write_cert(
                &compact,
                b"-----BEGIN CERTIFICATE-----\naGVsbG8gY2VydAo=\n-----END CERTIFICATE-----\n",
            );
            write_cert(
                &wrapped,
                b"-----BEGIN CERTIFICATE-----\n\naGVs\nbG8gY2VydAo=\n\n-----END CERTIFICATE-----\n",
            );

            assert_eq!(
                read_fingerprint(&compact).unwrap(),
                read_fingerprint(&wrapped).unwrap()
            );
        });
    }

    #[test]
    fn test_export_copies_file_and_creates_parent_dirs() {
        with_temp_coast_home(|home| {
            let source = home
                .join("caddy")
                .join("pki")
                .join("authorities")
                .join("local")
                .join("root.crt");
            write_cert(&source, b"test cert");
            let dest = home.join("exports").join("nested").join("coast-root.crt");

            execute_export(&dest).unwrap();

            assert_eq!(fs::read(&dest).unwrap(), b"test cert");
        });
    }

    #[test]
    fn test_missing_cert_reports_actionable_guidance() {
        with_temp_coast_home(|_| {
            let path = root_cert_path().unwrap();
            let err = ensure_cert_readable(&path).unwrap_err().to_string();
            assert!(err.contains("No Coast root certificate found"));
            assert!(err.contains("Caddy-backed HTTPS service"));
        });
    }

    #[test]
    fn test_unreadable_source_file_returns_clear_error() {
        with_temp_coast_home(|home| {
            let dir_as_file = home
                .join("caddy")
                .join("pki")
                .join("authorities")
                .join("local")
                .join("root.crt");
            fs::create_dir_all(&dir_as_file).unwrap();
            let err = read_fingerprint(&dir_as_file).unwrap_err().to_string();
            assert!(err.contains("not a file"));
        });
    }

    #[cfg(unix)]
    #[test]
    fn test_unreadable_cert_reports_permission_guidance() {
        use std::os::unix::fs::PermissionsExt;

        with_temp_coast_home(|home| {
            let cert_path = home
                .join("caddy")
                .join("pki")
                .join("authorities")
                .join("local")
                .join("root.crt");
            write_cert(&cert_path, b"test cert");

            let local_dir = cert_path.parent().unwrap().to_path_buf();
            let original_mode = fs::metadata(&local_dir).unwrap().permissions().mode();
            fs::set_permissions(&local_dir, fs::Permissions::from_mode(0o000)).unwrap();

            let err = ensure_cert_readable(&cert_path).unwrap_err().to_string();

            fs::set_permissions(&local_dir, fs::Permissions::from_mode(original_mode)).unwrap();

            assert!(err.contains("exists at"));
            assert!(err.contains("not readable"));
        });
    }
}
